addons:
  apt:
    packages:
    - libgmp-dev
    - pandoc
  homebrew:
    packages:
    - pandoc
    update: true

cache:
  directories:
  - $HOME/.local/bin
  - $HOME/.stack

env:
  global:
  - secure: "p89qrHUQqDptBMnHxfQzrSFFrm8dCdWv0Nfn7yllzyLtUphM+w8YugnbyLsb1R6PZqv4HJdjfl21B0yavzXoowrOupZ3SazwxIj3YgFn3GUFuaUWw1ghLd1NYvejOH1FcuqC/39qY+GkexmzRbxl0ePGFYVeUgOjLaw4/HzTEDum3LN3d/1Uy+4ZAcea1p0zK+HKI3O7NTbRMgZZVv6+ta3nkNYl4Mwp3b2nb3oSOa4QLCtiAyahOuFDnkfCJ86fzHZ401tIX9ahRwiR+a131PGwkdqMdJRcoCSy6XlpbmsmeGOKfMz3HuLRAcCR8oRPJwM21n5vFa5G5jnO1dipuCejSlFLljUo+R6qfZQEisupFQudz5SlR3SqqWl3fIqJ+/6TBM9Gf/ROv9uru1srxZoY1QeX/1GGSZXfBhK6DGhv+IyvnYKyV0bN+xRuYFGEawiqosVObaUi6sAm3/JBzNzTuuPT3uRo80bYZIugADucSYvdb5VKURFxMN7UVPpR2L6UM6uqZMzXm5ywCwaN3tMpXMq2KgM8lsoQTRR0i1zG7MaHb1s2WKXUDnvAxoxLbJr+cTdAFe3gIuLzutaRkS6frIpgU68BgwAZIEl6yyvuq8kiwlo8XwFJ5yt7A3mlFSAIfk37LQCJ/H/wdrU3OGraeeOzuxQ9xFE3hKyPlj8="

language: c

os:
- linux
- osx

sudo: false

before_install:
- travis_scripts/install_stack
- travis_scripts/install_github-release

script:
- stack setup
- stack --no-terminal build --no-run-benchmarks --pedantic
- stack sdist
- ./make_man_page

after_success:
- travis_scripts/attach_binary
