addons:
  apt:
    packages:
    - libgmp-dev
    - pandoc
  homebrew:
    packages:
    - pandoc

cache:
  directories:
  - $HOME/.local/bin
  - $HOME/.stack

env:
  global:
  - secure: "q1+2mag/XWHmOxTF7UVIdI8CEikX0YplEvD9lk/6//y2KcPB5NsN5tIgTSRFOcnsffjaRYRw11kYujqFoZIP7pNdcBUQi0pIG3p18Rkw0cx+qtBUjQD8RMHTDTxCteQJqdg6JyK9gphA3dy4GDzy9UXk1qrGQQ6CGZ9xPAShONYG7JXO8J1SUd2wFdfj50vzJiVlHTmkFGksh9If2QJKsrzbkGPiA8W+1leb1KCEtHCITZu5M37hMtTq9r4F+hqmlxvrf9rENPqkllDIDx3z+K39nPUHaigFcfHSoOZriSmS0K6ztwIxe1WbnlmwQzY+1CWqI3q3iv4Y6vBGbUWCFn/c1qcuWDns37K4b+e2v1ICF2XSsnRpmvjBIqiHhX84q6Gtt66P1yccjSENHHqYZW9+OYkyd8PiKLTctXxwtUwWylo6ill5MhwlWomYdSM0nmLd8/VNOSgXVjtqAmHz29+3L6H++WMU8UPER1wwOMbkiakA52AmOGnZcIpSNv1/pzaYgGgmZ3l6sHYMqwYKBHvtDoO70OJtWb5yVKJn+Kzag4FsEhJWRkhj+zNrlOeQhfjeVLylUUzqTeFGP1ggR7CAzTyOZP4P4hLECRfDa/Vz1Yn81y91WO7hZBqUWS2J1ZME66LkKdwIwZ2u2AEWhkHs2+0ib0fSAaVGxWKFBtM="

language: c

os:
- linux
- osx

sudo: false

before_install:
- travis_scripts/install_stack
- travis_scripts/install_github-release

script:
- stack setup
- stack --no-terminal build --no-run-benchmarks --pedantic
- stack sdist
- pandoc --to man --standalone --output pnbackup.1 man_page.md

after_success:
- travis_scripts/attach_binary
