#!/bin/bash

set -o errexit -o verbose

PROJECT_NAME=pinboard-notes-backup
BINARY_NAME=pnbackup

TRAVIS_TAG="v1.0.4"

if [[ -z "$TRAVIS_TAG" ]]; then
	echo "This is not a release build."
elif [[ -z "$GITHUB_TOKEN" ]]; then
	echo "The GITHUB_TOKEN environment variable is not set!"
	exit 1
else
	echo "Attaching binary for $TRAVIS_OS_NAME to $TRAVIS_TAG..."

	BINARY_FILE="$(stack path --local-install-root)/bin/$BINARY_NAME"
	chmod +x "$BINARY_FILE"

	LABEL=$PROJECT_NAME-$TRAVIS_TAG-$TRAVIS_OS_NAME
	mkdir "$LABEL"
	cp README.md LICENSE.txt pnbackup.1 "$BINARY_FILE" "$LABEL"
	tar -czvf "$LABEL.tar.gz" "$LABEL"

	github-release upload \
		--token "$GITHUB_TOKEN" \
		--owner bdesham \
		--repo "$PROJECT_NAME" \
		--tag "$TRAVIS_TAG" \
		--file "$LABEL.tar.gz" \
		--name "$LABEL.tar.gz"
fi
