name: Build
on: push
jobs:
  cabal-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ["8.6", "8.8", "8.10", "9.0"]
        cabal: ["2.4", "3.4", "3.6"]
        os: [ubuntu-latest, macOS-latest]
        # GHC 8.8 and later require Cabal 3
        exclude:
          - cabal: 2.4
            ghc: 8.8
          - cabal: 2.4
            ghc: 8.10
          - cabal: 2.4
            ghc: 9.0
    name: Cabal ${{ matrix.cabal }} and GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Retrieve .cabal from cache
        uses: actions/cache@v3
        env:
          cache-name: cache-cabal
        with:
          path: "~/.cabal"
          key: "cabal-${{ runner.os }}-ghc-${{ matrix.ghc }}"
          restore-keys: |
            cabal-${{ runner.os }}-ghc-${{ matrix.ghc }}-
            cabal-${{ runner.os }}-

      - name: Set up Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
          enable-stack: false

      - name: Cabal update
        run: cabal v2-update

      - name: Cabal freeze
        run: cabal v2-freeze

      - name: Cabal build
        run: cabal v2-build

  stack-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    name: Stack on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Retrieve .stack from cache
        uses: actions/cache@v3
        env:
          cache-name: cache-stack-work
        with:
          path: "~/.stack"
          key: "stack-${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}"
          restore-keys: |
            stack-${{ runner.os }}-

      - name: Set up Haskell
        uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          stack-version: latest

      - name: Build
        run: |
          stack --no-terminal build --no-run-benchmarks --pedantic
          mkdir dist
          stack --no-terminal install --local-bin-path=dist
          chmod u+x dist/pnbackup

      - name: Set environment variables
        if: "${{ startsWith(github.ref, 'refs/tags/v') }}"
        run: |
          REF=${{ github.ref }}
          VERSION=${REF/refs\/tags\/v/}
          LABEL=pinboard-notes-backup-$VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "LABEL=$LABEL" >> $GITHUB_ENV

      - name: Create release tarball
        if: "${{ startsWith(github.ref, 'refs/tags/v') }}"
        run: |
          OS=$(echo "${{ runner.os }}" | tr '[A-Z]' '[a-z]')
          mkdir $LABEL
          stack --no-terminal install --local-bin-path=$LABEL
          cp README.md LICENSE.txt man/pnbackup.1 $LABEL
          tar -czvf $LABEL-$OS.tar.gz $LABEL

      - name: Add release assets
        uses: softprops/action-gh-release@e99df7cd8088d9c5dddab02bf975f62025a6e760
        if: "${{ startsWith(github.ref, 'refs/tags/v') }}"
        with:
          draft: true
          files: "pinboard-notes-backup-*.tar.gz"
          fail_on_unmatched_files: true
          name: "Version ${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
