name: Build
on: push
defaults:
  run:
    shell: bash
jobs:
  cabal-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            ghc: "8.6"
            cabal: latest
          - os: ubuntu-latest
            ghc: "8.8"
            cabal: latest
          - os: ubuntu-latest
            ghc: "8.10"
            cabal: latest
          - os: ubuntu-latest
            ghc: "9.0"
            cabal: latest
          - os: ubuntu-latest
            ghc: "9.2"
            cabal: latest
          - os: ubuntu-latest
            ghc: "9.4"
            cabal: latest
          - os: ubuntu-latest
            ghc: "9.6"
            cabal: latest
          - os: ubuntu-latest
            ghc: "9.8"
            cabal: latest
          - os: ubuntu-latest
            ghc: "9.10"
            cabal: latest
          # Test with older versions of Cabal
          - os: ubuntu-latest
            ghc: "8.6"
            cabal: "2.4"
          - os: ubuntu-latest
            ghc: "9.8"
            cabal: "3.6"
          # Test the oldest and newest supported GHCs on macOS
          - os: macOS-latest
            ghc: "8.10"
            cabal: latest
          - os: macOS-latest
            ghc: "9.10"
            cabal: latest
    name: Cabal ${{ matrix.cabal }} and GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Retrieve .cabal from cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        env:
          cache-name: cache-cabal
        with:
          path: "~/.cabal"
          key: "cabal-${{ runner.os }}-ghc-${{ matrix.ghc }}"
          restore-keys: |
            cabal-${{ runner.os }}-ghc-${{ matrix.ghc }}-
            cabal-${{ runner.os }}-

      - name: Set up Haskell
        uses: haskell-actions/setup@cd0d9bdd65b20557f41bea4dbe43d0b5fbbfe553 # v2.11.0
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
          enable-stack: false

      - name: Cabal update
        run: cabal v2-update

      - name: Cabal freeze
        run: cabal v2-freeze

      - name: Cabal build
        run: cabal v2-build

      - name: Run the application
        run: cabal run -- --version

  stack-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    name: Stack on ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Retrieve .stack from cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        env:
          cache-name: cache-stack-work
        with:
          path: "~/.stack"
          key: "stack-${{ runner.os }}-${{ hashFiles('stack.yaml.lock') }}"
          restore-keys: |
            stack-${{ runner.os }}-

      - name: Set up Haskell
        uses: haskell-actions/setup@cd0d9bdd65b20557f41bea4dbe43d0b5fbbfe553 # v2.11.0
        with:
          enable-stack: true
          stack-version: latest

      - name: Build
        run: |
          stack --no-terminal build --no-run-benchmarks
          mkdir dist
          stack --no-terminal install --local-bin-path=dist
          chmod u+x dist/pnbackup

      - name: Run the application
        run: stack --no-terminal exec pnbackup -- --version

      - name: Set environment variables
        if: "startsWith(github.ref, 'refs/tags/v')"
        run: |
          REF="${{ github.ref }}"
          VERSION="${REF/refs\/tags\/v/}"
          LABEL="pinboard-notes-backup-$VERSION"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "LABEL=$LABEL" >> "$GITHUB_ENV"

      - name: Create release tarball
        if: "startsWith(github.ref, 'refs/tags/v')"
        env:
          OS: ${{ runner.os }}
        run: |
          LOWERCASE_OS="$(tr '[:upper:]' '[:lower:]' <<< "$OS")"
          mkdir "$LABEL"
          stack --no-terminal install --local-bin-path="$LABEL"
          cp README.md LICENSE.txt man/pnbackup.1 "$LABEL"
          tar -czvf "$LABEL-$LOWERCASE_OS.tar.gz" "$LABEL"

      - name: Add release assets
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        if: "startsWith(github.ref, 'refs/tags/v')"
        with:
          draft: true
          files: "pinboard-notes-backup-*.tar.gz"
          fail_on_unmatched_files: true
          name: "Version ${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
